### ISSUE TITLE
Amélioration provisioning

### ISSUE THREAD

**Issue by Crocmagnon** [Crocmagnon/plant-badger#5]
Pour l'instant, il faut changer manuellement les infos dans secrets.py avant de provisioner chaque carte.

On pourrait créer un fichier de provisioning de ce genre:
```yaml
e6614864d336b436:
  plant_id: plant.peperomia_obtusifolia
  moisture_sensor: sensor.peperomia_obtusifolia_soil_moisture
  temperature_sensor: sensor.peperomia_obtusifolia_temperature
  conductivity_sensor: sensor.peperomia_obtusifolia_conductivity
  illuminance_sensor: sensor.peperomia_obtusifolia_illuminance
```

Le script de setup pourrait alors boucler sur toutes les cartes connectées et ça faciliterait les mises à jour.
